import { ThemeProvider } from "@/components/providers/theme-provider"
import "@/styles/globals.css"
import type { Metadata } from "next"
import { Inter, JetBrains_Mono } from "next/font/google"

/**
 * Fonte Inter do Google Fonts, configurada para uso em todo o aplicativo.
 * Fonte sans-serif padrão do site.
 */
const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
})

/**
 * Fonte JetBrains Mono do Google Fonts, configurada para uso em todo o aplicativo.
 * Fonte monoespaçada para códigos e determinados elementos.
 */
const jetBrainsMono = JetBrains_Mono({
  variable: "--font-jetbrains-mono",
  subsets: ["latin"],
})

/**
 * Metadados para a aplicação.
 */
export const metadata: Metadata = {
  // TODO: Personalizar metadados
  title: "Create Next App",
  description: "Generated by create next app",
}

/**
 * Layout raiz do aplicativo.
 * Envolve toda a aplicação, definindo a estrutura HTML básica, provedores,
 * e estilos globais.
 */
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html
      lang="pt-br" // idioma do site
      suppressHydrationWarning // suprime avisos de hidratação para evitar problemas de renderização
      className={`${inter.variable} ${jetBrainsMono.variable}`}
    >
      <body className="antialiased">
        {/* Configuração de tema */}
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem // permite usar o tema do sistema operacional
          disableTransitionOnChange
        >
          {children} {/* Páginas e layouts aninhados */}
        </ThemeProvider>
      </body>
    </html>
  )
}
